### ISSUE TITLE
UX: Implement icon hover 

### ISSUE THREAD

**Issue by priyansh1161** [ryzokuken/ryzokuken.github.io#7]
Change colors of icons to Dark Green or actual logo color of linked websites.

**Comment by ryzokuken** [comment]
I tried the second choice, believe me, they look best this way.

**Comment by priyansh1161** [comment]
If you say so, but how about playing with font-weight?
giving different font-weight to main heading and subheading will really look neat. right now everything is completely bold.

**Comment by ryzokuken** [comment]
Yeah, agreed.
